name: Python package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install with Poetry
        run: |
          export $(grep -v '^#' .env | xargs)
          echo $LD_LIBRARY_PATH
          echo $MUJOCO_PY_MUJOCO_PATH
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
        shell: bash
      - name: Test with pytest
        run: |
          poetry run pytest
        shell: bash